import type {
  LayoutModeConfig,
  RenderTemplateVersion,
} from './render-model.js';
import { FEED_HEIGHT, FEED_WIDTH } from './render-model.js';

const layoutModes: LayoutModeConfig[] = [
  {
    id: 'HERO',
    minSelections: 1,
    maxSelections: 1,
    cardHeight: 660,
    cardGap: 0,
    cardPaddingX: 44,
    cardPaddingY: 44,
    teamFontSize: 48,
    teamFontMinSize: 28,
    marketFontSize: 34,
    marketFontMinSize: 24,
    metadataFontSize: 24,
    oddFontSize: 52,
    logoSize: 110,
  },
  {
    id: 'LARGE',
    minSelections: 2,
    maxSelections: 3,
    cardHeight: 280,
    cardGap: 22,
    cardPaddingX: 34,
    cardPaddingY: 28,
    teamFontSize: 36,
    teamFontMinSize: 23,
    marketFontSize: 26,
    marketFontMinSize: 19,
    metadataFontSize: 19,
    oddFontSize: 34,
    logoSize: 82,
  },
  {
    id: 'MEDIUM',
    minSelections: 4,
    maxSelections: 6,
    cardHeight: 140,
    cardGap: 12,
    cardPaddingX: 26,
    cardPaddingY: 18,
    teamFontSize: 27,
    teamFontMinSize: 18,
    marketFontSize: 20,
    marketFontMinSize: 15,
    metadataFontSize: 15,
    oddFontSize: 28,
    logoSize: 54,
  },
  {
    id: 'COMPACT',
    minSelections: 7,
    maxSelections: 8,
    cardHeight: 102,
    cardGap: 8,
    cardPaddingX: 22,
    cardPaddingY: 13,
    teamFontSize: 22,
    teamFontMinSize: 15,
    marketFontSize: 17,
    marketFontMinSize: 13,
    metadataFontSize: 13,
    oddFontSize: 24,
    logoSize: 40,
  },
  {
    id: 'ULTRA_COMPACT',
    minSelections: 9,
    maxSelections: 10,
    cardHeight: 78,
    cardGap: 8,
    cardPaddingX: 18,
    cardPaddingY: 10,
    teamFontSize: 16,
    teamFontMinSize: 12,
    marketFontSize: 15,
    marketFontMinSize: 12,
    metadataFontSize: 12,
    oddFontSize: 18,
    logoSize: 28,
  },
];

export const betStudioFeedTemplateV1: RenderTemplateVersion = {
  templateCode: 'BETSTUDIO_FEED',
  version: 1,
  format: 'FEED',
  canvas: { width: FEED_WIDTH, height: FEED_HEIGHT },
  locale: 'pt-PT',
  timezone: 'Europe/Lisbon',
  colors: {
    background: '#050608',
    panel: '#10141b',
    panelStrong: '#171d27',
    textPrimary: '#f8fafc',
    textSecondary: '#cbd5e1',
    textMuted: '#7f8da3',
    accent: '#c6ff3d',
    accentSecondary: '#7c3aed',
    border: '#2a3342',
    status: {
      PENDING: '#94a3b8',
      GREEN: '#c6ff3d',
      RED: '#fb7185',
      VOID: '#a1a1aa',
      MANUAL: '#c084fc',
    },
  },
  typography: {
    fontFamily: 'Arial, Helvetica, sans-serif',
  },
  regions: {
    header: { x: 64, y: 56, width: 952, height: 170 },
    selections: { x: 64, y: 250, width: 952, height: 900 },
    summary: { x: 64, y: 1184, width: 952, height: 90 },
    footer: { x: 64, y: 1300, width: 952, height: 28 },
  },
  layoutModes,
};
